spring:
  profiles:
    active: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  task:
      scheduling:
        pool:
          size: 10

mybatis:
  type-aliases-package: org.vite.gateway.model.dao.mapper.generated
  mapper-locations: classpath*:mapper/*.xml

server:
  port: 8082
  servlet:
    context-path: /

logging:
  config: classpath:logback.xml
